#!C:\Users\tito\Desktop\Kivy-dev\Python27\python.exe
# EASY-INSTALL-SCRIPT: 'Kivy-Garden==0.1.1','garden'
__requires__ = 'Kivy-Garden==0.1.1'
import pkg_resources
pkg_resources.run_script('Kivy-Garden==0.1.1', 'garden')
